on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/10 * * * *'

jobs:
  run-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            boo.bash
          sparse-checkout-cone-mode: true
      - name: Run script
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          ls
        
