on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/10 * * * *'

jobs:
  run-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          bash boo.bash