on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/10 * * * *'

jobs:        
  run-nim:
    runs-on: ubuntu-latest
    steps:
      - name: download binary from artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: boo-nim
          workflow: build-nim.yml

      - name: run binary
        run: |
          chmod +x boo
          ./boo